name: "my-website"
navbar:
  title: "TEAM HOPE"
  left:
    - text: "Home"
      href: index.html
    - text: "Demographics"
      href: demographics.html
    - text: "Crime Map"
      href: crime_map.html
    - text: "Statistics"
      href: statistics.html
    - text: "Appendix"
      href: appendix.html
output:
  html_document: 
    theme: cosmo
    highlight: textmate
  