name: "my-website"
navbar:
  title: "Jim's Policy Blog"
  left:
    - text: "Home"
      href: index.html
    - text: "Public Health"
      menu:
        - text: "NIH Neuroimaging"
          href: DICOM_learning.html
    - text: "Public Safety"
      menu:
        - text: "Fire - San Francisco"
          href: under_construction.html
        - text: "Crime"
          href: under_construction.html
    - text: "Cool Maps"
      menu: 
        - text: "Team Hope"
          href: interactive_map.html
        - text: "International Economics"
          href: world_sample.html
    - text: "Author"
      href: about.html

output:
  html_document: 
    theme: cosmo
    highlight: textmate
  