name: "my-website"
navbar:
  title: "Public Analyst Blog"
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
    - text: "Statistics"
      href: statistics.html

output:
  html_document: 
    theme: cosmo
    highlight: textmate
  