name: "my-website"
navbar:
  title: "Jim's Policy Blog"
  left:
    - text: "Home"
      href: index.html
    - text: "Demographics"
      href: demographics.html
    - text: "Interactive Maps"
      menu: 
        - text: "Heading 1"
        - text: "Fire Data"
          href: interactive_map.html
        - text: "Team Hope"
          href: interactive_map.html
        - text: "International Economics"
          href: world_sample.html
    - text: "Statistics"
      href: statistics.html
    - text: "Author"
      href: about.html
    - text: "Appendix"
      href: appendix.html

output:
  html_document: 
    theme: cosmo
    highlight: textmate
  