name: "my-website"
navbar:
  title: "TEAM HOPE"
  left:
    - text: "Home"
      href: index.html
    - text: "Crime Map"
      href: Crime Map.html
    - text: "Statistics"
      href: statistics.html


output:
  html_document: 
    theme: cosmo
    highlight: textmate
  