<head>
<style>
.hr { 
    display: block;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
    margin-left: auto;
    margin-right: auto;
    border-style: inset;
    border-width: 1px;
    width: 60%;
}
.abstract {
    -webkit-column-count: 1; /* Chrome, Safari, Opera */
    -moz-column-count: 1; /* Firefox */
    column-count: 1;
    -moz-column-width: 80%; /* Firefox */
    width: 80%;
    min-width: 300px;
    max-width: 500px;
    height: 50%
}
.newspaper1 {
    -webkit-column-count: 1; /* Chrome, Safari, Opera */
    -moz-column-count: 1; /* Firefox */
    column-count: 1;
    -moz-column-width: 80%; /* Firefox */
    width: 80%;
    min-width: 300px;
    max-width: 600px;
    height: 50%
}
.newspaper2 {
    -webkit-column-count: 2; /* Chrome, Safari, Opera */
    -moz-column-count: 2; /* Firefox */
    column-count: 2;
    -moz-column-width: 80%; /* Firefox */
    width: 80%;
    min-width: 300px;
    max-width: 600px;
    height: 50%
}
.code1 { 
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 80%;
    max-width: 600px;
}
.code2 {
    -webkit-column-count: 1; /* Chrome, Safari, Opera */
    -moz-column-count: 1; /* Firefox */
    column-count: 1;
    -moz-column-width: 80%; /* Firefox */
    width: 80%;
    min-width: 300px;
    max-width: 600px;
    height: 50%
}
<link rel="stylesheet" href="css/animate.css">
<script src="js/wow.min.js"> </script>
<script> new WOW().init(); </script>
</style>
<script type="text/javascript">
    window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
      heap.load("2042091030");
</script>
</head>

<iframe width="100%" height="800px" src="attach/UL/ul_safety_index_map.html" frameBorder="0" scrolling="no"></iframe>
<br><br>

<div class="code1">
<p style="text-align: left;">
```{r, eval = FALSE}
# This map was created using the plotly demo
library(plotly)
line <- list(color = toRGB("grey"), width = 0.4)

geo <- list(
  showframe = FALSE,
  showcoastlines = FALSE,
  projection = list(type = 'Mercator'),
  landcolor = toRGB("white"),
  bgcolor = "#ffffff"
)

map <- plot_geo(dat1, color = "#CCD2D4") %>%
  add_trace(
    z = ~ul_safety_index, 
    color = ~ul_safety_index, 
    colors = c("#F5A064", "#B70030", "#610039"),
    text = ~country, 
    locations = ~CODE, 
    marker = list(line = line)
  ) %>%
  colorbar(title = 'Safety Score', ticksuffix = '%') %>%
  layout(
    title = 'Global Safety Index<br>Source:<a href="http://www.ulsafetyindex.org/app/#view/map">Underwriters Laboratories</a>',
    geo = geo
  )
map
```
</p></div>